/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09.remotecrypto.servers;

import cat.uvic.teknos.m09.remotecrypto.connections.ConnectionTerminalServerTerminalClient;

import java.io.*;
import java.net.ServerSocket;

public class TerminalServer {
    private static final int SERVER_SOURCE_PORT=50001;
    public static void main(String[] args) throws IOException {
        var serverSocket=new ServerSocket(SERVER_SOURCE_PORT);
        while (true) {
            var clientSocket=serverSocket.accept();
            Thread thread=new Thread(new ConnectionTerminalServerTerminalClient(clientSocket)::clientConnection);
            thread.start();
        }
    }
}
